services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY
    command: uv run --no-dev uvicorn service:app --app-dir src --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./carton_caps.db:/app/carton_caps.db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: uv.lock